### ISSUE TITLE
Add argos.sc.omtrdc.net

### ISSUE THREAD

**Issue by JamesKingdom** [JamesKingdom/blocked-hosts#3]
Add the host `argos.sc.omtrdc.net` to list.txt
See [CONTRIBUTING](https://github.com/JamesKingdom/blocked-hosts/blob/gh-pages/CONTRIBUTING.md) for help.

**Comment by damcclean** [comment]
I'll work on this 👍

**Comment by damcclean** [comment]
Added to list
